### ISSUE TITLE
See if the `modulator` crate can cross-compile

### ISSUE THREAD

**Issue by LucvandenBrand** [LucvandenBrand/WiiDevEnv#11]
https://crates.io/crates/modulator looks pretty neat, but I have a feeling it uses the `std` lib.

**Comment by Qqwy** [comment]
The core `Modulator` trait and its provided implementations does not seem to use `std`. The provided `ModulatorEnv` does rely on a hashmap, but we can probably roll our own alternative ModulatorEnv that wraps a 'no-std' hashmap (allocated in 'a static large enough buffer' or similar) very easily.
We might need to extract the interesting code snippets from the `modulator` crate rather than use it directly, but I think it should be possible without much work.
